### ISSUE TITLE
JSONField cannot be used with unique=True in MySQL

### ISSUE THREAD

**Issue by etiennepouliot** [imsweb/django-saml-sp#12]
>2021-11-17T16:11:03.46-0500 [APP/TASK/migrate/0] ERR django.db.utils.OperationalError: (3152, "JSON column 'url_params' cannot be used in key specification.")

see details : https://code.djangoproject.com/ticket/2495

**Comment by dcwatson** [comment]
0.5 will remove this constraint, leaving it up to the application. Seems like a reasonable ask, since those params are application-specific anyway.
