### ISSUE TITLE
Valid certification expire date set in Metadata xml

### ISSUE THREAD

**Issue by nishitchittora** [imsweb/django-saml-sp#9]
Currently, metadata XML doesn't set a valid expire date. 

So, in code of [onelogin/python3-saml](https://github.com/onelogin/python3-saml/blob/ef2efa7d5a114b689d2344a2ce97dae37797b32a/src/onelogin/saml2/metadata.py#L64
) set 2 days valid date

```
        if valid_until is None:
            valid_until = int(time()) + cls.TIME_VALID
```

where    ` TIME_VALID = 172800   # 2 days`

which is not correct. Ideally it should be certificate expire date

**Comment by nishitchittora** [comment]
@dcwatson I have created this [PR](https://github.com/imsweb/django-saml-sp/pull/10).

**Comment by dcwatson** [comment]
Done as part of d8aad81452e9e28ef1d7e85e35dff7f271a86aa8
